files:
  - source: upload/admin/language/en-gb/
    translation: upload/admin/language/%locale%/
  - source: upload/catalog/language/en-gb/
    translation: upload/catalog/language/%locale%/
  - source: upload/install/language/en-gb/
    translation: upload/install/language/%locale%/
  - source: upload/extension/opencart/admin/language/en-gb/
    translation: upload/extension/opencart/admin/language/%locale%/
  - source: upload/extension/opencart/catalog/language/en-gb/
    translation: upload/extension/opencart/catalog/language/%locale%/
